### ISSUE TITLE
Upload models to the Hugging Face Hub 

### ISSUE THREAD

**Issue by adeenayakup** [gabegrand/world-models#1]
Hi!

Very cool work! It would be nice to have the model checkpoints on the [Hugging Face Hub](https://huggingface.co/models) rather than a Dropbox link

Some of the benefits of sharing your models through the Hub would be:

* versioning, commit history and diffs
* repos provide useful metadata about their tasks, languages, metrics, etc that make them discoverable
* multiple features from TensorBoard visualizations, PapersWithCode integration, and more
* wider reach of your work to the ecosystem

Creating the repos and adding new models should be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/models-uploading) explaining the process in case you're interested. Please let us know if you would be interested and if you have any questions.

**Comment by gabegrand** [comment]
Hi @adeenayakup -- thank you for reaching out about the HuggingFace hub. Since we're currently using pretrained LLMs through OpenAI, we don't have any model checkpoints associated with this project. If we end up training any custom models, we'll consider adding them to HuggingFace.
