### ISSUE TITLE
Leverage Reflexion for better codegen

### ISSUE THREAD

**Issue by LifeIsStrange** [gabegrand/world-models#2]
Hi @gabegrand friendly ping
Reality is indeed isomorphic to our mental semantic spaces and this paper seems very interesting!

If I understand correctly the process described in the paper is in two phases and the first is to use an LLM to generate a program, such as Codex or GPT-4.
The thing is, if we look at the reference benchmark [leaderboard ](https://paperswithcode.com/sota/code-generation-on-humaneval) on code generation,  Codex has 28.81% in accuracy, GPT-4 has a mere 67%, while the recent paper Reflexion, which is a modification/augmentation of GPT-4 has a remarkable accuracy of **91%**
https://paperswithcode.com/paper/reflexion-an-autonomous-agent-with-dynamic

**Comment by gabegrand** [comment]
Hi @LifeIsStrange, thanks for reaching out. I have read the Reflexion paper and certainly find it to be an exciting direction. As we note in our paper, there are many possible LLMs that could work for translating NL to PPL code; and we make no claims about Codex being optimal for this task. Models like Reflexion could certainly offer even better language-to-code performance.

**Comment by gabegrand** [comment]
Regarding this repo, I'd like to reserve the open issues section for people who are looking to work with our probabilistic world models and have questions or issues with the Church code. For that reason, I'm going to go ahead and close this issue for now. Please feel free to email me if you are interested in discussing follow-up work.

Best,
Gabe
